# User ver 3 -> some program can not use ver3 -> stay with v2
# Yes, just put Dockerfile path into docker-compose then they will find and read
version: '2'

services:
  web:
    # Build from default dockerfile
    build: .
    image: loitd/nginx-php7:dev
    # Command to execute
    # command: python manage.py runserver 0.0.0.0:8000
    # command: /opt/loitd/start.sh
    # Overwrite entrypoint if need
    # entrypoint: [php, -d, vendor/bin/phpunit]
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"
    # depends_on:
    #   - db